### ISSUE TITLE
Fails to compile using Flutter 3.3.2

### ISSUE THREAD

**Issue by ilaurillard** [ekasetiawans/flutter_background_service#211]
Hi there .. i encountered some problems:

Launching lib/main.dart on Nokia 7 2 in debug mode...
/home/ilaurillard/.pub-cache/hosted/pub.dartlang.org/flutter_background_service_android-2.3.2/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java:302: error: local variable data is accessed from within inner class; needs to be declared final
                        methodChannel.invokeMethod("onReceiveData", data);
                                                                    ^

Do you know whats might be the problem here?

**Comment by ilaurillard** [comment]
sorry and thanks for your great work!
